//      

import * as React from 'react';
import ScalingCellSizeAndPositionManager from './utils/ScalingCellSizeAndPositionManager';

                                                                   

                                  
                      
                       
                     
              
                 
                   
                
  

                                                                           

                                                          
                                                 

                                       
                       
                             
                                                                  
                           
                          
                                    
                                     
                       
                             
                 
                                                               
                        
                       
                     
                    
                         
                                   
                               
                            
  

                                 
                                  
                        

                                                                 

                                               

                                                              

                      
                       
                      
                       
                     
                    
                      
  

                                       
                      
                    
               
  

                               
                                   
                                  
                           
                          
                                
                               
                        
                       
  

                                           
                                                                    
                                       

                                                                 
                          

                                                  
                    

                                                               
                             

                                    
                     

                                  
                    
  

                               
                             
                            
  

                                     
                                      
                     

                                                            

                                
                 
                
  
